####
# ATENTION:
# Replace all occurences of appTasks with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:

  # MySQL Data
  appTasks-mysql-data:
    driver: local

  # Redis Data
  appTasks-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: appTasks-mysql
    volumes:
      - appTasks-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=appTasks
      - MYSQL_DATABASE=DBTASKS
      - MYSQL_USER=appTasks
      - MYSQL_PASSWORD=appTasks

  # Redis
  cache:
    image: redis:4.0
    container_name: appTasks-redis
    command: --appendonly yes
    volumes:
      - appTasks-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: appTasks-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache
